version: '3.1'

services:
  mongo:
    container_name: urls-mongo
    image: mongo
    restart: always
    volumes:
      - /mnt/persistent/url-shortener/:/data/db
    networks:
      urls:
        aliases:
          - mongo
  url-shortener:
    container_name: url-shortener
    context: ../../
    restart: always
    environment: 
      - NODE_ENV: production
      - MONGO_URI: mongodb://mongo:27017/url-shortener
    networks:
      urls:
        aliases:
          - url-shortener

networks:
  urls: